<a href="https://colab.research.google.com/github/oyrslufe/ESAA/blob/main/ESAA%200427%20assignment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 09 분류 실습- 캐글 산탄데르 고객 만족 예측

In [6]:
!pip install xgboost==1.7.6
!pip install lightgbm==4.1.0

Requirement already satisfied: xgboost==1.7.6 in /usr/local/lib/python3.12/dist-packages (1.7.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost==1.7.6) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost==1.7.6) (1.16.3)
Requirement already satisfied: lightgbm==4.1.0 in /usr/local/lib/python3.12/dist-packages (4.1.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from lightgbm==4.1.0) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm==4.1.0) (1.16.3)

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import warnings

warnings.filterwarnings('ignore')
cust_df = pd.read_csv('train_santander.csv', encoding='latin-1')
print('dataset shape:', cust_df.shape)
cust_df.head(3)

dataset shape: (76020, 371)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.17,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.03,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.77,0

In [8]:
cust_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

float:111, int:260으로 모든 피처가 숫자형이며 Null값은 없음

전체 데이터에서 만족 불만족 비율 보기

In [9]:
print(cust_df['TARGET'].value_counts())
unsatisfied_cnt = cust_df[cust_df['TARGET'] ==1].TARGET.count()
total_cnt = cust_df.TARGET.count()
print('unsatisfied 비율은 {0:.2f}'.format((unsatisfied_cnt / total_cnt)))

TARGET
0    73012
1     3008
Name: count, dtype: int64
unsatisfied 비율은 0.04

In [10]:
cust_df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [11]:
cust_df['var3'].replace(-999999, 2, inplace=True)
cust_df.drop('ID', axis=1, inplace=True)

# 피처 세트와 레이블 세트 분리, 레이블 칼럼은 DataFrame의 맨 마지막에 위치해 칼럼 위치 -1로 분리
X_features = cust_df.iloc[:, :-1]
y_labels = cust_df.iloc[:, -1]
print('피처 데이터 shape:{0}'.format(X_features.shape))

피처 데이터 shape:(76020, 369)

In [12]:
# 학습 데이터 세트와 테스트 데이터 세트를 분리
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_features, y_labels, test_size=0.2, random_state=0)

train_cnt = y_train.count()
test_cnt = y_test.count()
print('학습 세트 Shape:{0}, 테스트 세트 Shape:{1}'.format(X_train.shape, X_test.shape))

print('학습 세트 레이블 값 분포 비율')
print(y_train.value_counts()/train_cnt)
print('\n 테스트 세트 레이블 값 분포 비율')
print(y_test.value_counts()/test_cnt)

학습 세트 Shape:(60816, 369), 테스트 세트 Shape:(15204, 369)
학습 세트 레이블 값 분포 비율
TARGET
0    0.960964
1    0.039036
Name: count, dtype: float64

 테스트 세트 레이블 값 분포 비율
TARGET
0    0.9583
1    0.0417
Name: count, dtype: float64

학습, 테스트 데이터 세트 모두 타겟 값의 분포가 원본 데이터와 유사하게 만들어짐

early stopping을 위해 학습 데이터세트 쪼개기

In [13]:
# X_train, y_train을 다시 학습 검증 데이터 세트로 분리.
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

# XGBoost 모델의 학습과 하이퍼 파라미터 튜닝

In [14]:
# XGBoost의 학습 모델을 생성하고 예측 결과를 ROC AUC로 평가
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

# n_estimators는 500으로, random state는 예제 수행 시마다 동일 예측 결과를 위해 설정
xgb_clf = XGBClassifier(n_estimators=500, learning_rate=0.05, random_state=156)

# 성능 평가 지표를 auc로, 조기 중단 파라미터는 100으로 설정하고 학습 수행
xgb_clf.fit(X_tr, y_tr, early_stopping_rounds=100, eval_metric="auc", eval_set=[(X_tr,y_tr),(X_val,y_val)])

xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:,1])
print('ROC AUC: {0:.4f}'.format(xgb_roc_score))

[0]	validation_0-auc:0.82179	validation_1-auc:0.80068
[1]	validation_0-auc:0.82347	validation_1-auc:0.80523
[2]	validation_0-auc:0.83178	validation_1-auc:0.81097
[3]	validation_0-auc:0.83401	validation_1-auc:0.81091
[4]	validation_0-auc:0.83443	validation_1-auc:0.81040
[5]	validation_0-auc:0.83570	validation_1-auc:0.81089
[6]	validation_0-auc:0.83597	validation_1-auc:0.81057
[7]	validation_0-auc:0.83643	validation_1-auc:0.81082
[8]	validation_0-auc:0.83682	validation_1-auc:0.81147
[9]	validation_0-auc:0.83769	validation_1-auc:0.81188
[10]	validation_0-auc:0.83770	validation_1-auc:0.81163
[11]	validation_0-auc:0.83911	validation_1-auc:0.81355
[12]	validation_0-auc:0.83976	validation_1-auc:0.81336
[13]	validation_0-auc:0.84038	validation_1-auc:0.81365
[14]	validation_0-auc:0.84176	validation_1-auc:0.81419
[15]	validation_0-auc:0.84306	validation_1-auc:0.81586
[16]	validation_0-auc:0.84343	validation_1-auc:0.81610
[17]	validation_0-auc:0.84373	validation_1-auc:0.81584
[18]	validation_0-auc:0.84542	validation_1-auc:0.81581
[19]	validation_0-auc:0.84580	validation_1-auc:0.81622
[20]	validation_0-auc:0.84656	validation_1-auc:0.81641
[21]	validation_0-auc:0.84732	validation_1-auc:0.81740
[22]	validation_0-auc:0.84769	validation_1-auc:0.81748
[23]	validation_0-auc:0.84833	validation_1-auc:0.81744
[24]	validation_0-auc:0.84836	validation_1-auc:0.81704
[25]	validation_0-auc:0.84892	validation_1-auc:0.81650
[26]	validation_0-auc:0.85114	validation_1-auc:0.81730
[27]	validation_0-auc:0.85293	validation_1-auc:0.81843
[28]	validation_0-auc:0.85335	validation_1-auc:0.81883
[29]	validation_0-auc:0.85441	validation_1-auc:0.82072
[30]	validation_0-auc:0.85604	validation_1-auc:0.82169
[31]	validation_0-auc:0.85755	validation_1-auc:0.82256
[32]	validation_0-auc:0.85830	validation_1-auc:0.82267
[33]	validation_0-auc:0.85895	validation_1-auc:0.82321
[34]	validation_0-auc:0.85964	validation_1-auc:0.82332
[35]	validation_0-auc:0.85988	validation_1-auc:0.82408
[36]	validation_0-auc:0.86037	validation_1-auc:0.82452
[37]	validation_0-auc:0.86075	validation_1-auc:0.82466
[38]	validation_0-auc:0.86171	validation_1-auc:0.82554
[39]	validation_0-auc:0.86241	validation_1-auc:0.82582
[40]	validation_0-auc:0.86277	validation_1-auc:0.82590
[41]	validation_0-auc:0.86347	validation_1-auc:0.82628
[42]	validation_0-auc:0.86401	validation_1-auc:0.82668
[43]	validation_0-auc:0.86473	validation_1-auc:0.82686
[44]	validation_0-auc:0.86523	validation_1-auc:0.82692
[45]	validation_0-auc:0.86622	validation_1-auc:0.82774
[46]	validation_0-auc:0.86721	validation_1-auc:0.82834
[47]	validation_0-auc:0.86776	validation_1-auc:0.82831
[48]	validation_0-auc:0.86837	validation_1-auc:0.82909
[49]	validation_0-auc:0.86916	validation_1-auc:0.82997
[50]	validation_0-auc:0.86939	validation_1-auc:0.82984
[51]	validation_0-auc:0.87005	validation_1-auc:0.83006
[52]	validation_0-auc:0.87057	validation_1-auc:0.83039
[53]	validation_0-auc:0.87088	validation_1-auc:0.83066
[54]	validation_0-auc:0.87145	validation_1-auc:0.83105
[55]	validation_0-auc:0.87222	validation_1-auc:0.83139
[56]	validation_0-auc:0.87285	validation_1-auc:0.83167
[57]	validation_0-auc:0.87329	validation_1-auc:0.83175
[58]	validation_0-auc:0.87375	validation_1-auc:0.83170
[59]	validation_0-auc:0.87419	validation_1-auc:0.83196
[60]	validation_0-auc:0.87465	validation_1-auc:0.83191
[61]	validation_0-auc:0.87537	validation_1-auc:0.83186
[62]	validation_0-auc:0.87612	validation_1-auc:0.83187
[63]	validation_0-auc:0.87663	validation_1-auc:0.83192
[64]	validation_0-auc:0.87751	validation_1-auc:0.83194
[65]	validation_0-auc:0.87825	validation_1-auc:0.83218
[66]	validation_0-auc:0.87880	validation_1-auc:0.83248
[67]	validation_0-auc:0.87937	validation_1-auc:0.83241
[68]	validation_0-auc:0.87980	validation_1-auc:0.83239
[69]	validation_0-auc:0.88044	validation_1-auc:0.83249
[70]	validation_0-auc:0.88105	validation_1-auc:0.83229
[71]	validation_0-auc:0.88163	validation_1-auc:0.83261
[72]	validation_0-auc:0.88212	validation_1-auc:0.83251
[73]	validation_0-auc:0.88263	validation_1-auc:0.83257
[74]	validation_0-auc:0.88311	validation_1-auc:0.83258
[75]	validation_0-auc:0.88357	validation_1-auc:0.83255
[76]	validation_0-auc:0.88411	validation_1-auc:0.83264
[77]	validation_0-auc:0.88458	validation_1-auc:0.83241
[78]	validation_0-auc:0.88490	validation_1-auc:0.83232
[79]	validation_0-auc:0.88539	validation_1-auc:0.83249
[80]	validation_0-auc:0.88609	validation_1-auc:0.83251
[81]	validation_0-auc:0.88656	validation_1-auc:0.83261
[82]	validation_0-auc:0.88688	validation_1-auc:0.83265
[83]	validation_0-auc:0.88735	validation_1-auc:0.83258
[84]	validation_0-auc:0.88770	validation_1-auc:0.83270
[85]	validation_0-auc:0.88825	validation_1-auc:0.83251
[86]	validation_0-auc:0.88890	validation_1-auc:0.83240
[87]	validation_0-auc:0.88928	validation_1-auc:0.83229
[88]	validation_0-auc:0.88958	validation_1-auc:0.83225
[89]	validation_0-auc:0.88997	validation_1-auc:0.83205
[90]	validation_0-auc:0.89030	validation_1-auc:0.83210
[91]	validation_0-auc:0.89067	validation_1-auc:0.83223
[92]	validation_0-auc:0.89098	validation_1-auc:0.83212
[93]	validation_0-auc:0.89125	validation_1-auc:0.83198
[94]	validation_0-auc:0.89166	validation_1-auc:0.83198
[95]	validation_0-auc:0.89191	validation_1-auc:0.83196
[96]	validation_0-auc:0.89219	validation_1-auc:0.83181
[97]	validation_0-auc:0.89253	validation_1-auc:0.83184
[98]	validation_0-auc:0.89286	validation_1-auc:0.83176
[99]	validation_0-auc:0.89310	validation_1-auc:0.83184
[100]	validation_0-auc:0.89337	validation_1-auc:0.83176
[101]	validation_0-auc:0.89375	validation_1-auc:0.83168
[102]	validation_0-auc:0.89392	validation_1-auc:0.83175
[103]	validation_0-auc:0.89418	validation_1-auc:0.83162
[104]	validation_0-auc:0.89446	validation_1-auc:0.83162
[105]	validation_0-auc:0.89483	validation_1-auc:0.83173
[106]	validation_0-auc:0.89530	validation_1-auc:0.83182
[107]	validation_0-auc:0.89551	validation_1-auc:0.83179
[108]	validation_0-auc:0.89576	validation_1-auc:0.83190
[109]	validation_0-auc:0.89621	validation_1-auc:0.83190
[110]	validation_0-auc:0.89631	validation_1-auc:0.83198
[111]	validation_0-auc:0.89645	validation_1-auc:0.83200
[112]	validation_0-auc:0.89657	validation_1-auc:0.83214
[113]	validation_0-auc:0.89690	validation_1-auc:0.83221
[114]	validation_0-auc:0.89720	validation_1-auc:0.83223
[115]	validation_0-auc:0.89735	validation_1-auc:0.83218
[116]	validation_0-auc:0.89769	validation_1-auc:0.83236
[117]	validation_0-auc:0.89799	validation_1-auc:0.83245
[118]	validation_0-auc:0.89851	validation_1-auc:0.83253
[119]	validation_0-auc:0.89868	validation_1-auc:0.83256
[120]	validation_0-auc:0.89875	validation_1-auc:0.83269
[121]	validation_0-auc:0.89930	validation_1-auc:0.83258
[122]	validation_0-auc:0.89939	validation_1-auc:0.83269
[123]	validation_0-auc:0.89989	validation_1-auc:0.83274
[124]	validation_0-auc:0.90029	validation_1-auc:0.83308
[125]	validation_0-auc:0.90067	validation_1-auc:0.83324
[126]	validation_0-auc:0.90115	validation_1-auc:0.83325
[127]	validation_0-auc:0.90124	validation_1-auc:0.83324
[128]	validation_0-auc:0.90147	validation_1-auc:0.83324
[129]	validation_0-auc:0.90185	validation_1-auc:0.83337
[130]	validation_0-auc:0.90211	validation_1-auc:0.83336
[131]	validation_0-auc:0.90236	validation_1-auc:0.83341
[132]	validation_0-auc:0.90266	validation_1-auc:0.83351
[133]	validation_0-auc:0.90290	validation_1-auc:0.83346
[134]	validation_0-auc:0.90299	validation_1-auc:0.83362
[135]	validation_0-auc:0.90310	validation_1-auc:0.83363
[136]	validation_0-auc:0.90327	validation_1-auc:0.83355
[137]	validation_0-auc:0.90330	validation_1-auc:0.83354
[138]	validation_0-auc:0.90337	validation_1-auc:0.83357
[139]	validation_0-auc:0.90353	validation_1-auc:0.83348
[140]	validation_0-auc:0.90363	validation_1-auc:0.83353
[141]	validation_0-auc:0.90371	validation_1-auc:0.83346
[142]	validation_0-auc:0.90395	validation_1-auc:0.83341
[143]	validation_0-auc:0.90397	validation_1-auc:0.83341
[144]	validation_0-auc:0.90422	validation_1-auc:0.83340
[145]	validation_0-auc:0.90446	validation_1-auc:0.83335
[146]	validation_0-auc:0.90467	validation_1-auc:0.83354
[147]	validation_0-auc:0.90482	validation_1-auc:0.83355
[148]	validation_0-auc:0.90484	validation_1-auc:0.83356
[149]	validation_0-auc:0.90500	validation_1-auc:0.83353
[150]	validation_0-auc:0.90513	validation_1-auc:0.83352
[151]	validation_0-auc:0.90531	validation_1-auc:0.83349
[152]	validation_0-auc:0.90548	validation_1-auc:0.83349
[153]	validation_0-auc:0.90551	validation_1-auc:0.83351
[154]	validation_0-auc:0.90563	validation_1-auc:0.83348
[155]	validation_0-auc:0.90572	validation_1-auc:0.83343
[156]	validation_0-auc:0.90579	validation_1-auc:0.83344
[157]	validation_0-auc:0.90591	validation_1-auc:0.83345
[158]	validation_0-auc:0.90621	validation_1-auc:0.83355
[159]	validation_0-auc:0.90630	validation_1-auc:0.83359
[160]	validation_0-auc:0.90643	validation_1-auc:0.83356
[161]	validation_0-auc:0.90657	validation_1-auc:0.83352
[162]	validation_0-auc:0.90672	validation_1-auc:0.83346
[163]	validation_0-auc:0.90694	validation_1-auc:0.83347
[164]	validation_0-auc:0.90714	validation_1-auc:0.83343
[165]	validation_0-auc:0.90720	validation_1-auc:0.83343
[166]	validation_0-auc:0.90727	validation_1-auc:0.83337
[167]	validation_0-auc:0.90730	validation_1-auc:0.83335
[168]	validation_0-auc:0.90737	validation_1-auc:0.83333
[169]	validation_0-auc:0.90741	validation_1-auc:0.83337
[170]	validation_0-auc:0.90772	validation_1-auc:0.83335
[171]	validation_0-auc:0.90778	validation_1-auc:0.83332
[172]	validation_0-auc:0.90781	validation_1-auc:0.83337
[173]	validation_0-auc:0.90786	validation_1-auc:0.83337
[174]	validation_0-auc:0.90797	validation_1-auc:0.83326
[175]	validation_0-auc:0.90802	validation_1-auc:0.83334
[176]	validation_0-auc:0.90818	validation_1-auc:0.83335
[177]	validation_0-auc:0.90832	validation_1-auc:0.83330
[178]	validation_0-auc:0.90836	validation_1-auc:0.83332
[179]	validation_0-auc:0.90850	validation_1-auc:0.83339
[180]	validation_0-auc:0.90856	validation_1-auc:0.83340
[181]	validation_0-auc:0.90864	validation_1-auc:0.83338
[182]	validation_0-auc:0.90890	validation_1-auc:0.83335
[183]	validation_0-auc:0.90899	validation_1-auc:0.83327
[184]	validation_0-auc:0.90902	validation_1-auc:0.83330
[185]	validation_0-auc:0.90913	validation_1-auc:0.83330
[186]	validation_0-auc:0.90934	validation_1-auc:0.83352
[187]	validation_0-auc:0.90939	validation_1-auc:0.83356
[188]	validation_0-auc:0.90947	validation_1-auc:0.83346
[189]	validation_0-auc:0.90955	validation_1-auc:0.83347
[190]	validation_0-auc:0.90978	validation_1-auc:0.83341
[191]	validation_0-auc:0.90982	validation_1-auc:0.83340
[192]	validation_0-auc:0.90987	validation_1-auc:0.83342
[193]	validation_0-auc:0.90999	validation_1-auc:0.83339
[194]	validation_0-auc:0.91010	validation_1-auc:0.83338
[195]	validation_0-auc:0.91015	validation_1-auc:0.83329
[196]	validation_0-auc:0.91018	validation_1-auc:0.83331
[197]	validation_0-auc:0.91021	validation_1-auc:0.83333
[198]	validation_0-auc:0.91029	validation_1-auc:0.83338
[199]	validation_0-auc:0.91050	validation_1-auc:0.83338
[200]	validation_0-auc:0.91056	validation_1-auc:0.83338
[201]	validation_0-auc:0.91061	validation_1-auc:0.83334
[202]	validation_0-auc:0.91065	validation_1-auc:0.83333
[203]	validation_0-auc:0.91068	validation_1-auc:0.83334
[204]	validation_0-auc:0.91079	validation_1-auc:0.83336
[205]	validation_0-auc:0.91091	validation_1-auc:0.83323
[206]	validation_0-auc:0.91098	validation_1-auc:0.83316
[207]	validation_0-auc:0.91119	validation_1-auc:0.83319
[208]	validation_0-auc:0.91131	validation_1-auc:0.83320
[209]	validation_0-auc:0.91160	validation_1-auc:0.83331
[210]	validation_0-auc:0.91165	validation_1-auc:0.83329
[211]	validation_0-auc:0.91182	validation_1-auc:0.83325
[212]	validation_0-auc:0.91189	validation_1-auc:0.83330
[213]	validation_0-auc:0.91198	validation_1-auc:0.83329
[214]	validation_0-auc:0.91219	validation_1-auc:0.83321
[215]	validation_0-auc:0.91225	validation_1-auc:0.83326
[216]	validation_0-auc:0.91228	validation_1-auc:0.83329
[217]	validation_0-auc:0.91234	validation_1-auc:0.83326
[218]	validation_0-auc:0.91258	validation_1-auc:0.83311
[219]	validation_0-auc:0.91269	validation_1-auc:0.83311
[220]	validation_0-auc:0.91279	validation_1-auc:0.83305
[221]	validation_0-auc:0.91301	validation_1-auc:0.83310
[222]	validation_0-auc:0.91311	validation_1-auc:0.83307
[223]	validation_0-auc:0.91318	validation_1-auc:0.83310
[224]	validation_0-auc:0.91333	validation_1-auc:0.83308
[225]	validation_0-auc:0.91340	validation_1-auc:0.83309
[226]	validation_0-auc:0.91340	validation_1-auc:0.83307
[227]	validation_0-auc:0.91357	validation_1-auc:0.83310
[228]	validation_0-auc:0.91360	validation_1-auc:0.83310
[229]	validation_0-auc:0.91367	validation_1-auc:0.83312
[230]	validation_0-auc:0.91378	validation_1-auc:0.83313
[231]	validation_0-auc:0.91382	validation_1-auc:0.83313
[232]	validation_0-auc:0.91383	validation_1-auc:0.83314
[233]	validation_0-auc:0.91405	validation_1-auc:0.83312
[234]	validation_0-auc:0.91414	validation_1-auc:0.83307
[235]	validation_0-auc:0.91415	validation_1-auc:0.83305
ROC AUC: 0.8429

In [15]:
from hyperopt import hp

# max_depth는 5에서 15까지 1 간격으로, min_child_weight는 1에서 6까지 1 간격으로
# colsample_bytree는 0.5에서 0.95 사이, learning_rate는 0.01에서 0.2 사이 정규 분포된 값으로 검색.
xgb_search_space = {'max_depth': hp.quniform('max_depth', 5, 15, 1),
                    'min_child_weight': hp.quniform('min_child_weight', 1, 6, 1),
                    'colsample_bytree': hp.uniform('colsample_bytree', 0.5, 0.95),
                    'learning_rate': hp.uniform('learning_rate', 0.01, 0.2)}

In [16]:
# 목적 함수 만들기
# 목적 함수는 3 Fold 교차 검증을 이용해 평균 ROC-AUC 값을 반환하되 -1을 곱해주어 최대 ROC-AUC 값이 최소 반환값이 되게 함

from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score

# fmin()에서 호출 시 search_space 값으로 XGBClassifier 교차 검증 학습 후 -1*roc_auc 평균 값을 반환.
def objective_func(search_space):
  xgb_clf = XGBClassifier(n_estimators=100,max_depth=int(search_space['max_depth']),
                            min_child_weight=int(search_space['min_child_weight']),
                            colsample_bytree=search_space['colsample_bytree'],
                            learning_rate=search_space['learning_rate'])

  # 3개 k-fold 방식으로 평가된 roc_auc 지표를 담는 list
  roc_auc_list = [ ]

  # 3개 k-fold 방식 적용
  kf = KFold(n_splits=3)
  # X_train을 다시 학습과 겁증용 데이터로 분리
  for tr_index, val_index in kf.split(X_train):
    # kf.split(X_train)으로 추출된 학습과 검증 index 값으로 학습과 검증 데이터 세트 분리
    X_tr, y_tr = X_train.iloc[tr_index], y_train.iloc[tr_index]
    X_val, y_val = X_train.iloc[val_index], y_train.iloc[val_index]

    # early stopping은 30회로 설정하고 추출된 학습과 검증 데이터로 XGBClassifier 학습 수행
    xgb_clf.fit(X_tr, y_tr, early_stopping_rounds=30, eval_metric="auc",
                eval_set=[(X_tr, y_tr), (X_val, y_val)])

    # 1로 예측한 확률값 추출 후 roc auc 계산하고 평균 roc auc 계산을 위해 list에 결과값 담음
    score = roc_auc_score(y_val, xgb_clf.predict_proba(X_val)[:,1])
    roc_auc_list.append(score)

  # 3개 k-fold로 계산된 roc_auc 값의 평균값을 반환하되,
  # HyperOpt는 목적함수의 최솟값을 위한 입력값을 찾으므로 -1을 곱한 뒤 반환
  return -1*np.mean(roc_auc_list)

In [17]:
from hyperopt import fmin, tpe, Trials

trials = Trials()

# fmin() 함수를 호출
# max_evals 지정된 횟수만큼 반복 후 목적함수의 최솟값을 가지는 최적 입력값 추출
best = fmin(
    fn=objective_func,
    space=xgb_search_space,
    algo=tpe.suggest,
    max_evals=50,  # 최대 반복 횟수를 지정합니다.
    trials=trials,
    rstate=np.random.default_rng(seed=30)
)

print('best:', best)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[24]	validation_0-auc:0.90590	validation_1-auc:0.82771
[25]	validation_0-auc:0.90669	validation_1-auc:0.82847
[26]	validation_0-auc:0.90836	validation_1-auc:0.82965
[27]	validation_0-auc:0.90970	validation_1-auc:0.82947
[28]	validation_0-auc:0.91131	validation_1-auc:0.83014
[29]	validation_0-auc:0.91183	validation_1-auc:0.83063
[30]	validation_0-auc:0.91203	validation_1-auc:0.83035
[31]	validation_0-auc:0.91254	validation_1-auc:0.83014
[32]	validation_0-auc:0.91333	validation_1-auc:0.82944
[33]	validation_0-auc:0.91352	validation_1-auc:0.82935
[34]	validation_0-auc:0.91388	validation_1-auc:0.82896
[35]	validation_0-auc:0.91421	validation_1-auc:0.82882
[36]	validation_0-auc:0.91417	validation_1-auc:0.82852
[37]	validation_0-auc:0.91460	validation_1-auc:0.82793
[38]	validation_0-auc:0.91527	validation_1-auc:0.82808
[39]	validation_0-auc:0.91558	validation_1-auc:0.82730
[40]	validation_0-auc:0.91637	validation_1-auc:0.82722
[41]	validation_0-auc:0.91699	validation_1-auc:0.82715
[42]	validation_0-auc:0.91708	validation_1-auc:0.82711
[43]	validation_0-auc:0.91793	validation_1-auc:0.82663
[44]	validation_0-auc:0.91894	validation_1-auc:0.82662
[45]	validation_0-auc:0.91918	validation_1-auc:0.82625
[46]	validation_0-auc:0.91934	validation_1-auc:0.82630
[47]	validation_0-auc:0.92002	validation_1-auc:0.82646
[48]	validation_0-auc:0.92138	validation_1-auc:0.82679
[49]	validation_0-auc:0.92218	validation_1-auc:0.82657
[50]	validation_0-auc:0.92237	validation_1-auc:0.82628
[51]	validation_0-auc:0.92277	validation_1-auc:0.82641
[52]	validation_0-auc:0.92309	validation_1-auc:0.82602
[53]	validation_0-auc:0.92358	validation_1-auc:0.82606
[54]	validation_0-auc:0.92414	validation_1-auc:0.82616
[55]	validation_0-auc:0.92454	validation_1-auc:0.82612
[56]	validation_0-auc:0.92512	validation_1-auc:0.82600
[57]	validation_0-auc:0.92535	validation_1-auc:0.82554
[58]	validation_0-auc:0.92571	validation_1-auc:0.82521
[59]	validation_0-auc:0.92643	validation_1-auc:0.82471
[0]	validation_0-auc:0.81503	validation_1-auc:0.80348
[1]	validation_0-auc:0.82507	validation_1-auc:0.80416
[2]	validation_0-auc:0.84401	validation_1-auc:0.82012
[3]	validation_0-auc:0.85011	validation_1-auc:0.82434
[4]	validation_0-auc:0.85275	validation_1-auc:0.82684
[5]	validation_0-auc:0.85869	validation_1-auc:0.82485
[6]	validation_0-auc:0.85941	validation_1-auc:0.82035
[7]	validation_0-auc:0.86553	validation_1-auc:0.82292
[8]	validation_0-auc:0.86777	validation_1-auc:0.82546
[9]	validation_0-auc:0.87046	validation_1-auc:0.82481
[10]	validation_0-auc:0.87009	validation_1-auc:0.81897
[11]	validation_0-auc:0.87820	validation_1-auc:0.82208
[12]	validation_0-auc:0.88447	validation_1-auc:0.82726
[13]	validation_0-auc:0.88616	validation_1-auc:0.82490
[14]	validation_0-auc:0.88956	validation_1-auc:0.82781
[15]	validation_0-auc:0.88945	validation_1-auc:0.82645
[16]	validation_0-auc:0.88928	validation_1-auc:0.82520
[17]	validation_0-auc:0.89054	validation_1-auc:0.82232
[18]	validation_0-auc:0.89470	validation_1-auc:0.82563
[19]	validation_0-auc:0.89946	validation_1-auc:0.82686
[20]	validation_0-auc:0.90183	validation_1-auc:0.82799
[21]	validation_0-auc:0.90386	validation_1-auc:0.82697
[22]	validation_0-auc:0.90653	validation_1-auc:0.82836
[23]	validation_0-auc:0.90765	validation_1-auc:0.82919
[24]	validation_0-auc:0.90912	validation_1-auc:0.82940
[25]	validation_0-auc:0.91012	validation_1-auc:0.83046
[26]	validation_0-auc:0.91164	validation_1-auc:0.83094
[27]	validation_0-auc:0.91326	validation_1-auc:0.83102
[28]	validation_0-auc:0.91365	validation_1-auc:0.83091
[29]	validation_0-auc:0.91429	validation_1-auc:0.83142
[30]	validation_0-auc:0.91448	validation_1-auc:0.83157
[31]	validation_0-auc:0.91472	validation_1-auc:0.83120
[32]	validation_0-auc:0.91550	validation_1-auc:0.83080
[33]	validation_0-auc:0.91583	validation_1-auc:0.83110
[34]	validation_0-auc:0.91660	validation_1-auc:0.83092
[35]	validation_0-auc:0.91697	validation_1-auc:0.83054
[36]	validation_0-auc:0.91782	validation_1-auc:0.83026
[37]	validation_0-auc:0.91815	validation_1-auc:0.83016
[38]	validation_0-auc:0.91923	validation_1-auc:0.82952
[39]	validation_0-auc:0.91979	validation_1-auc:0.82934
[40]	validation_0-auc:0.92092	validation_1-auc:0.82973
[41]	validation_0-auc:0.92132	validation_1-auc:0.82938
[42]	validation_0-auc:0.92203	validation_1-auc:0.82956
[43]	validation_0-auc:0.92299	validation_1-auc:0.82918
[44]	validation_0-auc:0.92338	validation_1-auc:0.82931
[45]	validation_0-auc:0.92489	validation_1-auc:0.82810
[46]	validation_0-auc:0.92500	validation_1-auc:0.82813
[47]	validation_0-auc:0.92655	validation_1-auc:0.82814
[48]	validation_0-auc:0.92688	validation_1-auc:0.82810
[49]	validation_0-auc:0.92718	validation_1-auc:0.82805
[50]	validation_0-auc:0.92739	validation_1-auc:0.82789
[51]	validation_0-auc:0.92794	validation_1-auc:0.82796
[52]	validation_0-auc:0.92807	validation_1-auc:0.82802
[53]	validation_0-auc:0.92858	validation_1-auc:0.82762
[54]	validation_0-auc:0.92871	validation_1-auc:0.82728
[55]	validation_0-auc:0.92886	validation_1-auc:0.82727
[56]	validation_0-auc:0.92898	validation_1-auc:0.82721
[57]	validation_0-auc:0.92908	validation_1-auc:0.82741
[58]	validation_0-auc:0.92917	validation_1-auc:0.82756
[59]	validation_0-auc:0.92937	validation_1-auc:0.82763
[60]	validation_0-auc:0.92961	validation_1-auc:0.82744
[0]	validation_0-auc:0.82307	validation_1-auc:0.80544
[1]	validation_0-auc:0.82685	validation_1-auc:0.80708
[2]	validation_0-auc:0.83997	validation_1-auc:0.81535
[3]	validation_0-auc:0.84509	validation_1-auc:0.81952
[4]	validation_0-auc:0.85006	validation_1-auc:0.82413
[5]	validation_0-auc:0.85667	validation_1-auc:0.82295
[6]	validation_0-auc:0.85898	validation_1-auc:0.82039
[7]	validation_0-auc:0.86646	validation_1-auc:0.82467
[8]	validation_0-auc:0.86911	validation_1-auc:0.82616
[9]	validation_0-auc:0.87253	validation_1-auc:0.82486
[10]	validation_0-auc:0.87408	validation_1-auc:0.82003
[11]	validation_0-auc:0.87964	validation_1-auc:0.82392
[12]	validation_0-auc:0.88553	validation_1-auc:0.82714
[13]	validation_0-auc:0.88768	validation_1-auc:0.82663
[14]	validation_0-auc:0.89230	validation_1-auc:0.82903
[15]	validation_0-auc:0.89258	validation_1-auc:0.82686
[16]	validation_0-auc:0.89307	validation_1-auc:0.82368
[17]	validation_0-auc:0.89429	validation_1-auc:0.82203
[18]	validation_0-auc:0.89879	validation_1-auc:0.82577
[19]	validation_0-auc:0.90222	validation_1-auc:0.82728
[20]	validation_0-auc:0.90344	validation_1-auc:0.82798
[21]	validation_0-auc:0.90445	validation_1-auc:0.82706
[22]	validation_0-auc:0.90712	validation_1-auc:0.82920
[23]	validation_0-auc:0.90807	validation_1-auc:0.83113
[24]	validation_0-auc:0.90959	validation_1-auc:0.83054
[25]	validation_0-auc:0.91118	validation_1-auc:0.83161
[26]	validation_0-auc:0.91287	validation_1-auc:0.83239
[27]	validation_0-auc:0.91466	validation_1-auc:0.83171
[28]	validation_0-auc:0.91547	validation_1-auc:0.83106
[29]	validation_0-auc:0.91650	validation_1-auc:0.83193
[30]	validation_0-auc:0.91694	validation_1-auc:0.83228
[31]	validation_0-auc:0.91716	validation_1-auc:0.83195
[32]	validation_0-auc:0.91761	validation_1-auc:0.83170
[33]	validation_0-auc:0.91815	validation_1-auc:0.83237
[34]	validation_0-auc:0.91877	validation_1-auc:0.83241
[35]	validation_0-auc:0.91916	validation_1-auc:0.83232
[36]	validation_0-auc:0.91933	validation_1-auc:0.83264
[37]	validation_0-auc:0.91975	validation_1-auc:0.83234
[38]	validation_0-auc:0.92005	validation_1-auc:0.83223
[39]	validation_0-auc:0.92065	validation_1-auc:0.83207
[40]	validation_0-auc:0.92120	validation_1-auc:0.83247
[41]	validation_0-auc:0.92169	validation_1-auc:0.83280
[42]	validation_0-auc:0.92173	validation_1-auc:0.83276
[43]	validation_0-auc:0.92333	validation_1-auc:0.83270
[44]	validation_0-auc:0.92366	validation_1-auc:0.83299
[45]	validation_0-auc:0.92414	validation_1-auc:0.83306
[46]	validation_0-auc:0.92430	validation_1-auc:0.83278
[47]	validation_0-auc:0.92449	validation_1-auc:0.83265
[48]	validation_0-auc:0.92471	validation_1-auc:0.83225
[49]	validation_0-auc:0.92592	validation_1-auc:0.83174
[50]	validation_0-auc:0.92633	validation_1-auc:0.83175
[51]	validation_0-auc:0.92654	validation_1-auc:0.83164
[52]	validation_0-auc:0.92668	validation_1-auc:0.83153
[53]	validation_0-auc:0.92692	validation_1-auc:0.83134
[54]	validation_0-auc:0.92708	validation_1-auc:0.83145
[55]	validation_0-auc:0.92731	validation_1-auc:0.83125
[56]	validation_0-auc:0.92754	validation_1-auc:0.83132
[57]	validation_0-auc:0.92761	validation_1-auc:0.83096
[58]	validation_0-auc:0.92832	validation_1-auc:0.83086
[59]	validation_0-auc:0.92851	validation_1-auc:0.83059
[60]	validation_0-auc:0.92862	validation_1-auc:0.83062
[61]	validation_0-auc:0.92886	validation_1-auc:0.83052
[62]	validation_0-auc:0.92921	validation_1-auc:0.83037
[63]	validation_0-auc:0.92968	validation_1-auc:0.82983
[64]	validation_0-auc:0.92981	validation_1-auc:0.82938
[65]	validation_0-auc:0.92995	validation_1-auc:0.82941
[66]	validation_0-auc:0.93014	validation_1-auc:0.82903
[67]	validation_0-auc:0.93057	validation_1-auc:0.82850
[68]	validation_0-auc:0.93095	validation_1-auc:0.82863
[69]	validation_0-auc:0.93162	validation_1-auc:0.82860
[70]	validation_0-auc:0.93223	validation_1-auc:0.82806
[71]	validation_0-auc:0.93249	validation_1-auc:0.82757
[72]	validation_0-auc:0.93276	validation_1-auc:0.82729
[73]	validation_0-auc:0.93306	validation_1-auc:0.82733
[74]	validation_0-auc:0.93323	validation_1-auc:0.82751
[0]	validation_0-auc:0.82050	validation_1-auc:0.79942
[1]	validation_0-auc:0.81456	validation_1-auc:0.79081
[2]	validation_0-auc:0.83154	validation_1-auc:0.80456
[3]	validation_0-auc:0.83596	validation_1-auc:0.81078
[4]	validation_0-auc:0.84162	validation_1-auc:0.81523
[5]	validation_0-auc:0.84188	validation_1-auc:0.81290
[6]	validation_0-auc:0.84690	validation_1-auc:0.81870
[7]	validation_0-auc:0.84903	validation_1-auc:0.82010
[8]	validation_0-auc:0.85161	validation_1-auc:0.82275
[9]	validation_0-auc:0.85233	validation_1-auc:0.82291
[10]	validation_0-auc:0.85166	validation_1-auc:0.82025
[11]	validation_0-auc:0.85697	validation_1-auc:0.82235
[12]	validation_0-auc:0.85963	validation_1-auc:0.82454
[13]	validation_0-auc:0.86084	validation_1-auc:0.82467
[14]	validation_0-auc:0.86318	validation_1-auc:0.82706
[15]	validation_0-auc:0.86258	validation_1-auc:0.82511
[16]	validation_0-auc:0.86218	validation_1-auc:0.82454
[17]	validation_0-auc:0.86254	validation_1-auc:0.82305
[18]	validation_0-auc:0.86528	validation_1-auc:0.82647
[19]	validation_0-auc:0.86856	validation_1-auc:0.82834
[20]	validation_0-auc:0.87080	validation_1-auc:0.83150
[21]	validation_0-auc:0.87116	validation_1-auc:0.83067
[22]	validation_0-auc:0.87342	validation_1-auc:0.83233
[23]	validation_0-auc:0.87453	validation_1-auc:0.83249
[24]	validation_0-auc:0.87534	validation_1-auc:0.83179
[25]	validation_0-auc:0.87660	validation_1-auc:0.83246
[26]	validation_0-auc:0.87759	validation_1-auc:0.83289
[27]	validation_0-auc:0.87852	validation_1-auc:0.83330
[28]	validation_0-auc:0.87909	validation_1-auc:0.83369
[29]	validation_0-auc:0.87969	validation_1-auc:0.83470
[30]	validation_0-auc:0.88046	validation_1-auc:0.83420
[31]	validation_0-auc:0.88069	validation_1-auc:0.83381
[32]	validation_0-auc:0.88131	validation_1-auc:0.83379
[33]	validation_0-auc:0.88153	validation_1-auc:0.83377
[34]	validation_0-auc:0.88328	validation_1-auc:0.83322
[35]	validation_0-auc:0.88438	validation_1-auc:0.83262
[36]	validation_0-auc:0.88463	validation_1-auc:0.83258
[37]	validation_0-auc:0.88496	validation_1-auc:0.83214
[38]	validation_0-auc:0.88524	validation_1-auc:0.83221
[39]	validation_0-auc:0.88559	validation_1-auc:0.83179
[40]	validation_0-auc:0.88647	validation_1-auc:0.83180
[41]	validation_0-auc:0.88723	validation_1-auc:0.83152
[42]	validation_0-auc:0.88742	validation_1-auc:0.83156
[43]	validation_0-auc:0.88832	validation_1-auc:0.83166
[44]	validation_0-auc:0.88883	validation_1-auc:0.83146
[45]	validation_0-auc:0.88909	validation_1-auc:0.83136
[46]	validation_0-auc:0.88923	validation_1-auc:0.83114
[47]	validation_0-auc:0.89006	validation_1-auc:0.83165
[48]	validation_0-auc:0.89029	validation_1-auc:0.83170
[49]	validation_0-auc:0.89044	validation_1-auc:0.83132
[50]	validation_0-auc:0.89068	validation_1-auc:0.83120
[51]	validation_0-auc:0.89136	validation_1-auc:0.83104
[52]	validation_0-auc:0.89218	validation_1-auc:0.83077
[53]	validation_0-auc:0.89297	validation_1-auc:0.83097
[54]	validation_0-auc:0.89332	validation_1-auc:0.83089
[55]	validation_0-auc:0.89344	validation_1-auc:0.83093
[56]	validation_0-auc:0.89367	validation_1-auc:0.83082
[57]	validation_0-auc:0.89447	validation_1-auc:0.83046
[58]	validation_0-auc:0.89522	validation_1-auc:0.82994
[0]	validation_0-auc:0.81426	validation_1-auc:0.80325
[1]	validation_0-auc:0.81541	validation_1-auc:0.79608
[2]	validation_0-auc:0.83386	validation_1-auc:0.81858
[3]	validation_0-auc:0.84077	validation_1-auc:0.82367
[4]	validation_0-auc:0.84580	validation_1-auc:0.82782
[5]	validation_0-auc:0.84789	validation_1-auc:0.82467
[6]	validation_0-auc:0.85098	validation_1-auc:0.82812
[7]	validation_0-auc:0.85329	validation_1-auc:0.83078
[8]	validation_0-auc:0.85556	validation_1-auc:0.83150
[9]	validation_0-auc:0.85576	validation_1-auc:0.82979
[10]	validation_0-auc:0.85595	validation_1-auc:0.82712
[11]	validation_0-auc:0.85853	validation_1-auc:0.82863
[12]	validation_0-auc:0.86133	validation_1-auc:0.82885
[13]	validation_0-auc:0.86208	validation_1-auc:0.82741
[14]	validation_0-auc:0.86419	validation_1-auc:0.82924
[15]	validation_0-auc:0.86373	validation_1-auc:0.82693
[16]	validation_0-auc:0.86291	validation_1-auc:0.82626
[17]	validation_0-auc:0.86320	validation_1-auc:0.82470
[18]	validation_0-auc:0.86681	validation_1-auc:0.82809
[19]	validation_0-auc:0.86967	validation_1-auc:0.83011
[20]	validation_0-auc:0.87274	validation_1-auc:0.83253
[21]	validation_0-auc:0.87364	validation_1-auc:0.83206
[22]	validation_0-auc:0.87592	validation_1-auc:0.83314
[23]	validation_0-auc:0.87716	validation_1-auc:0.83428
[24]	validation_0-auc:0.87750	validation_1-auc:0.83380
[25]	validation_0-auc:0.87864	validation_1-auc:0.83484
[26]	validation_0-auc:0.87976	validation_1-auc:0.83590
[27]	validation_0-auc:0.88055	validation_1-auc:0.83576
[28]	validation_0-auc:0.88188	validation_1-auc:0.83576
[29]	validation_0-auc:0.88225	validation_1-auc:0.83634
[30]	validation_0-auc:0.88286	validation_1-auc:0.83667
[31]	validation_0-auc:0.88331	validation_1-auc:0.83676
[32]	validation_0-auc:0.88414	validation_1-auc:0.83645
[33]	validation_0-auc:0.88432	validation_1-auc:0.83680
[34]	validation_0-auc:0.88448	validation_1-auc:0.83706
[35]	validation_0-auc:0.88514	validation_1-auc:0.83719
[36]	validation_0-auc:0.88558	validation_1-auc:0.83737
[37]	validation_0-auc:0.88585	validation_1-auc:0.83732
[38]	validation_0-auc:0.88713	validation_1-auc:0.83681
[39]	validation_0-auc:0.88784	validation_1-auc:0.83648
[40]	validation_0-auc:0.88851	validation_1-auc:0.83681
[41]	validation_0-auc:0.88920	validation_1-auc:0.83711
[42]	validation_0-auc:0.88968	validation_1-auc:0.83666
[43]	validation_0-auc:0.89033	validation_1-auc:0.83607
[44]	validation_0-auc:0.89058	validation_1-auc:0.83631
[45]	validation_0-auc:0.89082	validation_1-auc:0.83587
[46]	validation_0-auc:0.89093	validation_1-auc:0.83586
[47]	validation_0-auc:0.89110	validation_1-auc:0.83562
[48]	validation_0-auc:0.89217	validation_1-auc:0.83570
[49]	validation_0-auc:0.89231	validation_1-auc:0.83578
[50]	validation_0-auc:0.89249	validation_1-auc:0.83571
[51]	validation_0-auc:0.89283	validation_1-auc:0.83561
[52]	validation_0-auc:0.89369	validation_1-auc:0.83540
[53]	validation_0-auc:0.89394	validation_1-auc:0.83538
[54]	validation_0-auc:0.89395	validation_1-auc:0.83535
[55]	validation_0-auc:0.89429	validation_1-auc:0.83520
[56]	validation_0-auc:0.89444	validation_1-auc:0.83514
[57]	validation_0-auc:0.89465	validation_1-auc:0.83507
[58]	validation_0-auc:0.89481	validation_1-auc:0.83495
[59]	validation_0-auc:0.89520	validation_1-auc:0.83497
[60]	validation_0-auc:0.89534	validation_1-auc:0.83504
[61]	validation_0-auc:0.89558	validation_1-auc:0.83497
[62]	validation_0-auc:0.89588	validation_1-auc:0.83469
[63]	validation_0-auc:0.89605	validation_1-auc:0.83452
[64]	validation_0-auc:0.89616	validation_1-auc:0.83430
[65]	validation_0-auc:0.89729	validation_1-auc:0.83412
[66]	validation_0-auc:0.89745	validation_1-auc:0.83405
[0]	validation_0-auc:0.82341	validation_1-auc:0.81148
[1]	validation_0-auc:0.82045	validation_1-auc:0.80641
[2]	validation_0-auc:0.83356	validation_1-auc:0.81834
[3]	validation_0-auc:0.83984	validation_1-auc:0.82135
[4]	validation_0-auc:0.84077	validation_1-auc:0.82203
[5]	validation_0-auc:0.84355	validation_1-auc:0.82355
[6]	validation_0-auc:0.84795	validation_1-auc:0.82651
[7]	validation_0-auc:0.84961	validation_1-auc:0.82844
[8]	validation_0-auc:0.85133	validation_1-auc:0.82936
[9]	validation_0-auc:0.85225	validation_1-auc:0.82876
[10]	validation_0-auc:0.85321	validation_1-auc:0.82596
[11]	validation_0-auc:0.85648	validation_1-auc:0.82738
[12]	validation_0-auc:0.85944	validation_1-auc:0.82870
[13]	validation_0-auc:0.85973	validation_1-auc:0.82716
[14]	validation_0-auc:0.86308	validation_1-auc:0.83001
[15]	validation_0-auc:0.86312	validation_1-auc:0.82868
[16]	validation_0-auc:0.86273	validation_1-auc:0.82787
[17]	validation_0-auc:0.86262	validation_1-auc:0.82684
[18]	validation_0-auc:0.86523	validation_1-auc:0.82953
[19]	validation_0-auc:0.86873	validation_1-auc:0.83198
[20]	validation_0-auc:0.87137	validation_1-auc:0.83394
[21]	validation_0-auc:0.87215	validation_1-auc:0.83378
[22]	validation_0-auc:0.87445	validation_1-auc:0.83458
[23]	validation_0-auc:0.87500	validation_1-auc:0.83628
[24]	validation_0-auc:0.87570	validation_1-auc:0.83634
[25]	validation_0-auc:0.87707	validation_1-auc:0.83681
[26]	validation_0-auc:0.87818	validation_1-auc:0.83726
[27]	validation_0-auc:0.87935	validation_1-auc:0.83783
[28]	validation_0-auc:0.88025	validation_1-auc:0.83741
[29]	validation_0-auc:0.88110	validation_1-auc:0.83814
[30]	validation_0-auc:0.88149	validation_1-auc:0.83847
[31]	validation_0-auc:0.88197	validation_1-auc:0.83816
[32]	validation_0-auc:0.88262	validation_1-auc:0.83770
[33]	validation_0-auc:0.88330	validation_1-auc:0.83780
[34]	validation_0-auc:0.88395	validation_1-auc:0.83732
[35]	validation_0-auc:0.88463	validation_1-auc:0.83731
[36]	validation_0-auc:0.88541	validation_1-auc:0.83818
[37]	validation_0-auc:0.88693	validation_1-auc:0.83782
[38]	validation_0-auc:0.88727	validation_1-auc:0.83775
[39]	validation_0-auc:0.88844	validation_1-auc:0.83710
[40]	validation_0-auc:0.88878	validation_1-auc:0.83712
[41]	validation_0-auc:0.88970	validation_1-auc:0.83768
[42]	validation_0-auc:0.89003	validation_1-auc:0.83795
[43]	validation_0-auc:0.89063	validation_1-auc:0.83820
[44]	validation_0-auc:0.89071	validation_1-auc:0.83855
[45]	validation_0-auc:0.89131	validation_1-auc:0.83879
[46]	validation_0-auc:0.89162	validation_1-auc:0.83883
[47]	validation_0-auc:0.89206	validation_1-auc:0.83884
[48]	validation_0-auc:0.89233	validation_1-auc:0.83855
[49]	validation_0-auc:0.89334	validation_1-auc:0.83865
[50]	validation_0-auc:0.89356	validation_1-auc:0.83843
[51]	validation_0-auc:0.89372	validation_1-auc:0.83834
[52]	validation_0-auc:0.89391	validation_1-auc:0.83848
[53]	validation_0-auc:0.89422	validation_1-auc:0.83862
[54]	validation_0-auc:0.89474	validation_1-auc:0.83841
[55]	validation_0-auc:0.89542	validation_1-auc:0.83811
[56]	validation_0-auc:0.89612	validation_1-auc:0.83770
[57]	validation_0-auc:0.89643	validation_1-auc:0.83768
[58]	validation_0-auc:0.89661	validation_1-auc:0.83783
[59]	validation_0-auc:0.89695	validation_1-auc:0.83768
[60]	validation_0-auc:0.89712	validation_1-auc:0.83748
[61]	validation_0-auc:0.89723	validation_1-auc:0.83731
[62]	validation_0-auc:0.89787	validation_1-auc:0.83733
[63]	validation_0-auc:0.89837	validation_1-auc:0.83695
[64]	validation_0-auc:0.89861	validation_1-auc:0.83676

In [18]:
# n_estimators를 500으로 증가 후 최적으로 찾은 하이퍼 파라미터를 기반으로 학습과 예측 수행
xgb_clf = XGBClassifier(
    n_estimators=500,
    learning_rate=round(best['learning_rate'], 5),
    max_depth=int(best['max_depth']),
    min_child_weight=int(best['min_child_weight']),
    colsample_bytree=round(best['colsample_bytree'], 5),
    eval_metric='auc',
    early_stopping_rounds=100,
    random_state=156
)

# evaluation metric을 auc로, early stopping은 100으로 설정하고 학습 수행
xgb_clf.fit(
    X_tr, y_tr,
    eval_set=[(X_tr, y_tr), (X_val, y_val)],
    verbose=False
)

xgb_roc_score = roc_auc_score(y_test, xgb_clf.predict_proba(X_test)[:, 1])
print('ROC AUC: {0:.4f}'.format(xgb_roc_score))

ROC AUC: 0.8451

In [ ]:
from xgboost import plot_importance
import matplotlib.pyplot as pit
%matplotlib inline

fig, ax = pit.subplots(1,1,figsize=(10, 8))
plot_importance(xgb_clf, ax=ax , max_num_features=20, height=0.4)

In [20]:
# 앞의 XGBoost 예제 코드에서 만들어진 데이터 세트를 기반으로 LightGBM으로 학습을 수행하고 ROC-AUC를 측정해보자
from lightgbm import LGBMClassifier, early_stopping # 수정

lgbm_clf = LGBMClassifier(n_estimators=500)

eval_set = [(X_tr, y_tr), (X_val, y_val)]
lgbm_clf.fit(
    X_tr, y_tr,
    eval_metric="auc",
    eval_set=eval_set,
    callbacks=[early_stopping(stopping_rounds=100)] # 여기에 조기 종료 설정이 들어갑니다.
) # 수정
lgbm_roc_score = roc_auc_score(y_test, lgbm_clf.predict_proba(X_test)[:, 1])
print('ROC AUC: {0:.4f}'.format(lgbm_roc_score))

[LightGBM] [Info] Number of positive: 1658, number of negative: 40913
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074083 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13308
[LightGBM] [Info] Number of data points in the train set: 42571, number of used features: 242
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038947 -> initscore=-3.205836
[LightGBM] [Info] Start training from score -3.205836
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[42]	training's auc: 0.91059	training's binary_logloss: 0.112183	valid_1's auc: 0.831787	valid_1's binary_logloss: 0.13527
ROC AUC: 0.8384

In [21]:
lgbm_search_space = {'num_leaves': hp.quniform('num_leaves', 32, 64, 1),
                     'max_depth': hp.quniform('max_depth', 100, 160, 1),
                     'min_child_samples': hp.quniform('min_child_samples', 60, 100, 1),
                     'subsample': hp.uniform('subsample', 0.7, 1),
                     'learning_rate': hp.uniform('learning_rate', 0.01, 0.2)
}

In [22]:
# 목적 함수 생성. 소스 코드는 앞 XGBoost와 크게 다르지 않으며 LGBMClassifier 객체를 생성하는 부분이 달라짐
def objective_func(search_space):
  lgbm_clf = LGBMClassifier(n_estimators=100,
                            num_leaves=int(search_space['num_leaves']),
                            max_depth=int(search_space['max_depth']),
                            min_child_samples=int(search_space['min_child_samples']),
                            subsample=search_space['subsample'],
                            learning_rate=search_space['learning_rate'])
  # 3개 k-fold 방식으로 평가된 roc_auc 지표를 담는 list
  roc_auc_list = []

  # 3개 k-fold 방식 적용
  kf = KFold(n_splits=3)
  # X_train을 다시 학습과 검증용 데이터로 분리
  for tr_index, val_index in kf.split(X_train):
    # kf.split(X_train)으로 추출된 학습과 겁증 index 값으로 학습과 검증 데이터 세트 분리
    X_tr, y_tr = X_train.iloc[tr_index], y_train.iloc[tr_index]
    X_val, y_val = X_train.iloc[val_index], y_train.iloc[val_index]

    # early stopping은 30회로 설정하고 추출된 학습과 검증 데이터로 XGBClassifier 학습 수행.
    lgbm_clf.fit(X_tr, y_tr,
                 eval_metric="auc",
                 eval_set=[(X_tr, y_tr), (X_val, y_val)],
                 callbacks=[early_stopping(stopping_rounds=30)])

    # 1로 예측한 확률값 추출 후 roc auc 계산하고 평균 roc auc 계산을 위해 list에 결과값 담음.
    score = roc_auc_score(y_val, lgbm_clf.predict_proba(X_val)[:,1])
    roc_auc_list.append(score)

  # 3개 k-fold로 계산된 roc_auc 값의 평균값을 반환하되,
  # HyperOpt는 목적함수의 최솟값을 위한 입력값을 찾으므로 -1을 곱한 뒤 반환.
  return -1*np.mean(roc_auc_list)

In [23]:
# fmin()을 호출하여 최적 하이퍼 파라미터 도출
from hyperopt import fmin, tpe, Trials

trials = Trials()

# fmin() 함수를 호출. max_evals 지정된 횟수만큼 반복 후 목적함수의 최솟값을 가지는 최적 입력값 추출
best = fmin(fn=objective_func, space=lgbm_search_space, algo=tpe.suggest,
            max_evals=50, # 최대 반복 횟수를 지정합니다.
            trials=trials, rstate=np.random.default_rng(seed=30))

print('best:', best)

[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.064399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12827
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[98]	training's auc: 0.88765	training's binary_logloss: 0.121808	valid_1's auc: 0.831519	valid_1's binary_logloss: 0.135868
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.096930 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13008
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[32]	training's auc: 0.860623	training's binary_logloss: 0.137851	valid_1's auc: 0.835706	valid_1's binary_logloss: 0.137481
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.077783 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12855
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[98]	training's auc: 0.885445	training's binary_logloss: 0.121577	valid_1's auc: 0.837538	valid_1's binary_logloss: 0.136446
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.069178 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12885
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[8]	training's auc: 0.876014	training's binary_logloss: 0.128648	valid_1's auc: 0.830458	valid_1's binary_logloss: 0.139332
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.066603 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13008
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[9]	training's auc: 0.876004	training's binary_logloss: 0.129519	valid_1's auc: 0.835219	valid_1's binary_logloss: 0.134005
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.065720 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12915
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[17]	training's auc: 0.897685	training's binary_logloss: 0.117316	valid_1's auc: 0.832056	valid_1's binary_logloss: 0.137878
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.108161 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12827
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[21]	training's auc: 0.880303	training's binary_logloss: 0.126597	valid_1's auc: 0.830448	valid_1's binary_logloss: 0.137992
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.065298 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12946
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[47]	training's auc: 0.903653	training's binary_logloss: 0.11734	valid_1's auc: 0.837037	valid_1's binary_logloss: 0.130606
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.064778 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12855
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[37]	training's auc: 0.896492	training's binary_logloss: 0.118202	valid_1's auc: 0.836576	valid_1's binary_logloss: 0.136794
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.066792 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12895
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 199
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[15]	training's auc: 0.891713	training's binary_logloss: 0.122226	valid_1's auc: 0.830818	valid_1's binary_logloss: 0.137184
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.072997 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13046
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 202
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[38]	training's auc: 0.92456	training's binary_logloss: 0.108961	valid_1's auc: 0.836448	valid_1's binary_logloss: 0.130846
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.116474 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12915
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[13]	training's auc: 0.886101	training's binary_logloss: 0.123542	valid_1's auc: 0.832306	valid_1's binary_logloss: 0.139844
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.069892 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12827
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[46]	training's auc: 0.905084	training's binary_logloss: 0.116011	valid_1's auc: 0.832359	valid_1's binary_logloss: 0.135612
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.066222 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12946
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[46]	training's auc: 0.902133	training's binary_logloss: 0.118038	valid_1's auc: 0.835118	valid_1's binary_logloss: 0.130885
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.067789 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12855
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[26]	training's auc: 0.884765	training's binary_logloss: 0.12408	valid_1's auc: 0.836094	valid_1's binary_logloss: 0.138359
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.102027 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12827
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[98]	training's auc: 0.875162	training's binary_logloss: 0.127906	valid_1's auc: 0.83007	valid_1's binary_logloss: 0.137948
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.066676 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13008
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[58]	training's auc: 0.863996	training's binary_logloss: 0.136878	valid_1's auc: 0.835763	valid_1's binary_logloss: 0.137074
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.067676 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12855
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[100]	training's auc: 0.875291	training's binary_logloss: 0.127136	valid_1's auc: 0.836234	valid_1's binary_logloss: 0.138892
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.064922 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12827
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[14]	training's auc: 0.883983	training's binary_logloss: 0.122742	valid_1's auc: 0.829439	valid_1's binary_logloss: 0.136732
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.099142 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12946
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[23]	training's auc: 0.898643	training's binary_logloss: 0.118736	valid_1's auc: 0.834012	valid_1's binary_logloss: 0.131262
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.070161 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12855
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[14]	training's auc: 0.882212	training's binary_logloss: 0.122057	valid_1's auc: 0.834167	valid_1's binary_logloss: 0.1375
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.069521 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12885
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[6]	training's auc: 0.877909	training's binary_logloss: 0.129022	valid_1's auc: 0.831019	valid_1's binary_logloss: 0.139605
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.068336 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 13008
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.039685 -> initscore=-3.186281
[LightGBM] [Info] Start training from score -3.186281
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[8]	training's auc: 0.882764	training's binary_logloss: 0.126909	valid_1's auc: 0.834978	valid_1's binary_logloss: 0.133306
[LightGBM] [Info] Number of positive: 1560, number of negative: 38984
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.065853 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12915
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 197
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038477 -> initscore=-3.218465
[LightGBM] [Info] Start training from score -3.218465
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[10]	training's auc: 0.888474	training's binary_logloss: 0.121393	valid_1's auc: 0.831905	valid_1's binary_logloss: 0.13881
[LightGBM] [Info] Number of positive: 1579, number of negative: 38965
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.068958 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12827
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.038945 -> initscore=-3.205872
[LightGBM] [Info] Start training from score -3.205872
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[16]	training's auc: 0.883463	training's binary_logloss: 0.122487	valid_1's auc: 0.828811	valid_1's binary_logloss: 0.136226
[LightGBM] [Info] Number of positive: 1609, number of negative: 38935
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.096727 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 12946
[LightGBM] [Info] Number of data points in the train set: 40544, number of used features: 192

In [ ]:
# 이들 하이퍼 파라미터를 이용하여 LightGBM을 학습 후에 테스트 데이터 세트에서 ROC-AUC를 평가
from lightgbm import early_stopping
from lightgbm import LGBMClassifier # 수정
from sklearn.metrics import roc_auc_score # 수

lgbm_clf = LGBMClassifier(n_estimators=500, num_leaves=int(best['num_leaves']),
                          max_depth=int(best['max_depth']),
                          min_child_samples=int(best['min_child_samples']),
                          subsample=round(best['subsample'], 5),
                          learning_rate=round(best['learning_rate'], 5)
)

# evaluation metric을 auc로, early stopping은 100으로 설정하고 학습 수행.
lgbm_clf.fit(X_tr, y_tr,
             eval_metric="auc",
             eval_set=[(X_tr, y_tr), (X_val, y_val)],
             callbacks=[early_stopping(stopping_rounds=100)]) # 수정

lgbm_roc_score = roc_auc_score(y_test,lgbm_clf.predict_proba(X_test)[:,1])
print('ROC AUC: {0:.4f}'.format(lgbm_roc_score))

In [ ]:
# SMOTE를 구현한 대표적인 파이썬 패키지 : imbalanced-learn
%pip install imbalanced-learn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

card_df = pd.read_csv('creditcard.csv')
card_df.head(3)

In [ ]:
from sklearn.model_selection import train_test_split

# 인자로 입력받은 DataFrame을 복사한 뒤 Time 칼럼만 삭제하고 복사된 DataFrame 반환
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  df_copy.drop('Time', axis=1, inplace=True)
  return df_copy

In [ ]:
# 사전 데이터 가공 후 학습과 테스트 데이터 세트를 반환하는 함수.
def get_train_test_dataset(df=None):
  # 인자로 입력된 DataFrame의 사전 데이터 가공이 완료된 복사 DataFrame 반환
  df_copy = get_preprocessed_df(df)
  # DataFrame의 맨 마지막 칼럼이 레이블, 나머지는 피처들
  X_features = df_copy.iloc[:,:-1]
  y_target = df_copy.iloc[:,-1]
  # train_test_split()으로 학습과 테스트 데이터 분할. stratify=y_target으로 Stratified 기반 분할
  X_train, X_test, y_train, y_test = \
  train_test_split(X_features, y_target, test_size=0.3, random_state=0, stratify=y_target)
  # 학습과 테스트 데이터 세트 반환
  return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

In [ ]:
print('학습 데이터 레이블 값 비율')
print(y_train.value_counts()/y_train.shape[0]*100)
print('테스트 데이터 레이블 값 비율')
print(y_test.value_counts()/y_test.shape[0]*100)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, roc_auc_score

# 파라미터를 3개(y_test, pred, pred_proba) 받도록 수정
def get_clf_eval(y_test, pred, pred_proba):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)

    # ROC AUC 계산 추가
    roc_auc = roc_auc_score(y_test, pred_proba)

    print('오차 행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, AUC: {3:.4f}'.format(accuracy, precision, recall, roc_auc))

In [ ]:
from sklearn.linear_model import LogisticRegression

Ir_clf = LogisticRegression(max_iter=1000)
Ir_clf.fit(X_train, y_train)
Ir_pred = Ir_clf.predict(X_test)
Ir_pred_proba = Ir_clf.predict_proba(X_test)[:,1]

# 3장에서 사용한 get_clf_eval() 함수를 이용해 평가 수행.
get_clf_eval(y_test, Ir_pred, Ir_pred_proba)

In [ ]:
# 인자로 사이킷런의 Estimator 객체와 학습/테스트 데이터 세트를 입력받아서 학습/예측/평가 수행.
def get_model_train_eval(model, ftr_train=None, ftr_test=None, tgt_train=None, tgt_test=None):
  model.fit(ftr_train, tgt_train)
  pred = model.predict(ftr_test)
  pred_proba = model.predict_proba(ftr_test)[:,1]
  get_clf_eval(tgt_test, pred, pred_proba)

In [ ]:
from lightgbm import LGBMClassifier

lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

In [ ]:
import seaborn as sns

plt.figure(figsize=(8,4))
plt.xticks(range(0,30000,1000), rotation=60)
sns.histplot(card_df['Amount'], bins=100, kde=True)
plt.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
# 사이킷런의 StandardScaler를 이용해 정규 분포 형태로 Amount 피처값 변환하는 로직으로 수정.
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  scaler = StandardScaler()
  amount_n = scaler.fit_transform(df_copy['Amount'].values.reshape(-1,1))
  # 변환된 Amount를 Amount_Scaled로 피처명 변경후 DataFrame 맨 앞 칼럼으로 입력
  df_copy.insert(0, 'Amount_Scaled', amount_n)
  # 기존 Time, Amount 피처 삭제
  df_copy.drop(['Time', 'Amount'], axis=1, inplace=True)
  return df_copy

In [ ]:
# Amount를 정규 분포 형태로 변환 후 로지스틱 회귀 및 LightGBM 수행.
X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)

print('### 로지스틱 회귀 예측 성능 ###')
lr_clf = LogisticRegression(max_iter=1000)
get_model_train_eval(lr_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

print('### LightGBM 예측 성능 ###')
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

In [ ]:
import seaborn as sns

plt.figure(figsize=(9,9))
corr = card_df.corr()
sns.heatmap(corr, cmap='RdBu')

In [ ]:
import numpy as np

def get_outlier(df=None, column=None, weight=1.5):
  # fraud에 해당하는 column 데이터만 추출, 1/4 분위와 3/4 분위 지점을 np.percentile로 구함.
  fraud = df[df['Class']==1][column]
  quantile_25 = np.percentile(fraud.values, 25)
  quantile_75 = np.percentile(fraud.values, 75)

  # IQR을 구하고, IQR에 1.5를 곱해 최댓값과 최솟값 지점 구함.
  iqr = quantile_75 - quantile_25
  iqr_weight = iqr * weight
  lowest_val = quantile_25 - iqr_weight
  highest_val = quantile_75 + iqr_weight

  # 최댓값보다 크거나, 최솟값보다 작은 값을 이상치 데이터로 설정하고 DataFrame index 반환.
  outlier_index = fraud[(fraud < lowest_val) | (fraud > highest_val)].index
  return outlier_index

In [ ]:
outlier_index = get_outlier(df=card_df, column='V14', weight=1.5)
print('이상치 데이터 인덱스:', outlier_index)

In [ ]:
# get_processed_df()를 로그 변환 후 V14 피처의 이상치 데이터를 삭제하는 로직으로 변경.
def get_preprocessed_df(df=None):
  df_copy = df.copy()
  amount_n = np.log1p(df_copy['Amount'])
  df_copy.insert(0, 'Amount_Scaled', amount_n)
  df_copy.drop(['Time', 'Amount'], axis=1, inplace=True)
  # 이상치 데이터 삭제하는 로직 추가
  outlier_index = get_outlier(df=df_copy, column='V14', weight=1.5)
  df_copy.drop(outlier_index, axis=0, inplace=True)
  return df_copy

X_train, X_test, y_train, y_test = get_train_test_dataset(card_df)
print('### 로지스틱 회귀 예측 성능 ###')
get_model_train_eval(lr_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)
print('### LightGBM 예측 성능 ###')
get_model_train_eval(lgbm_clf, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

In [ ]:
# 학습 데이터 세트만 오버 샘플링 해야 함.
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0)
X_train_over, y_train_over = smote.fit_resample(X_train, y_train)
print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', X_train.shape, y_train.shape)
print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', X_train_over.shape, y_train_over.shape)
print('SMOTE 적용 후 레이블 값 분포: \n', pd.Series(y_train_over).value_counts())

In [ ]:
lr_clf = LogisticRegression(max_iter=1000)
# ftr_train과 tgt_train 인자값이 SMOTE 증식된 X_train_over와 y_train_over로 변경됨에 유의
get_model_train_eval(lr_clf, ftr_train=X_train_over, ftr_test=X_test, tgt_train=y_train_over,
                     tgt_test=y_test)

In [ ]:
from sklearn.metrics import precision_recall_curve

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
%matplotlib inline

def precision_recall_curve_plot(y_test, pred_proba_c1):
  # threshold ndarray와 이 threshold에 따른 정밀도, 재현율 ndarray 추출.
  precisions, recalls, thresholds = precision_recall_curve(y_test, pred_proba_c1)

  # X축을 threshold값으로, Y축은 정밀도, 재현율 값으로 각각 Plot 수행. 정밀도는 점선으로 표시
  plt.figure(figsize=(8,6))
  threshold_boundary = thresholds.shape[0]
  plt.plot(thresholds, precisions[0:threshold_boundary], linestyle='--', label='precision')
  plt.plot(thresholds, recalls[0:threshold_boundary], label='recall')

  # threshold 값 X축의 Scale을 0.1 단위로 변경
  start, end = plt.xlim()
  plt.xticks(np.round(np.arange(start, end, 0.1), 2))

  # x축, y축 label과 legend, 그리고 grid 설정
  plt.xlabel('Threshold value'); plt.ylabel('Precision and Recall value')
  plt.legend(); plt.grid()
  plt.show()

In [ ]:
precision_recall_curve_plot(y_test, lr_clf.predict_proba(X_test)[:,1])

In [ ]:
lgbm_clf = LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
get_model_train_eval(lgbm_clf, ftr_train=X_train_over, ftr_test=X_test,
                     tgt_train=y_train_over, tgt_test=y_test)